[package]
name = "ja_tokenizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vibrato = "^0.5.0"
zstd = "^0.12.3"
clap = { version = "4.0", features = ["derive"] }  # MIT or Apache-2.0
